# Generated by Django 4.2.1 on 2023-05-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_project_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
