# Generated by Django 4.2.1 on 2023-05-22 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_skill_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
