# Generated by Django 4.2.1 on 2023-05-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_endorsement"),
    ]

    operations = [
        migrations.AddField(
            model_name="endorsement",
            name="approved",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="endorsement",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
