# Generated by Django 4.2.1 on 2023-05-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_comment_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
