# Generated by Django 4.2.1 on 2023-05-25 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_comment_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="logo",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
