# Generated by Django 4.2.1 on 2023-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_skill_logo_alter_skill_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="coffee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=50)),
                ("payment_id", models.CharField(max_length=50)),
                ("paid", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="skill",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
