# Generated by Django 4.2.1 on 2023-06-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_coffee_alter_skill_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffee",
            name="payment_id",
        ),
        migrations.AddField(
            model_name="coffee",
            name="order_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="coffee",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
