# Generated by Django 4.2.1 on 2023-06-09 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_coffee_payment_id_coffee_order_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("backend", "backend"),
                            ("frontend", "frontend"),
                            ("fullstack", "fullstack"),
                        ],
                        max_length=100,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
